# main paths
exp_path: Experiments

# train
annotations: "train.csv"
images: "data"

# validation
val_annotations: "val.csv"
val_images: "data"

# exp params
exp_name: unetplusplus_se_resnet101_Tversky_2
project: Lung_with_background

trainer:
  devices: [0]
  accelerator: gpu
  precision: 16
  max_epochs: 400
  sync_batchnorm: True
  gradient_clip_val: 1.0

start_from: 

loss:
  loss_type: Tversky
  ignore_index: -1

model:
  model_type: deeplabv3plus # unetplusplus #deeplabv3plus
  encoder_name: se_resnet101 # densenet161 #se_resnet101
  in_channels: 3
  num_classes: 22
  encoder_depth: 5


dataloader:
  batch_size: 30
  num_workers: 3

transforms:
  aug_prob: 1.0

optimizer: adam
optimizer_params:
  lr: 0.0005
  weight_decay: 0.0001

scheduler: cosine
scheduler_params:
  warmup_epochs: 1

checkpoint:
  monitor: loss/val
  filename: model
  mode: min
