# main paths
exp_path: Experiments

# exp params
exp_name: unet_resnet50_dice
project: mri_segmentation

trainer:
  devices: [3]
  accelerator: gpu
  precision: 16
  max_epochs: 30
  sync_batchnorm: True
  gradient_clip_val: 1.0

start_from: null

loss:
  loss_type: Dice
  ignore_index: -1

model:
  model_type: unet # [unet, unetplusplus, deeplabv3, deeplabv3plus, pan]
  encoder_name: resnet50 # [densenet161, se_resnet101]
  in_channels: 2
  num_classes: 4
  encoder_depth: 5


dataloader:
  batch_size: 2
  num_workers: 8

transforms:
  aug_prob: 1.0

optimizer: adam
optimizer_params:
  lr: 0.0005
  weight_decay: 0.0001

scheduler: cosine
scheduler_params:
  warmup_epochs: 1

checkpoint:
  monitor: loss/val
  filename: model
  mode: min
